### ISSUE TITLE
TypeError: Cannot read property 'getFullYear' of undefined

### ISSUE THREAD

**Issue by sanket101** [misha130/ion-datepicker#76]
I followed the steps specified for installing ion-datepicker module.
But when I tried to click on this clipboard icon in my app:

<span ion-datepicker  [(value)]="localDate" [min]="localDate" clear class="ScheduleDate">
		<span>{{localDate | date}} <ion-icon name="clipboard" item-left ></ion-icon> </span>
</span>

I get this type of error : 

Error: Uncaught (in promise): TypeError: Cannot read property 'getFullYear' of undefined
TypeError: Cannot read property 'getFullYear' of undefined
    at DateService.createDateList (http://localhost:8100/build/vendor.js:62124:51)
    at DatePickerComponent.createDateList (http://localhost:8100/build/vendor.js:61833:48)
    at DatePickerComponent.initialize (http://localhost:8100/build/vendor.js:61827:14)
    at new DatePickerComponent (http://localhost:8100/build/vendor.js:61819:14)
    at createClass (http://localhost:8100/build/vendor.js:12859:20)
    at createDirectiveInstance (http://localhost:8100/build/vendor.js:12700:37)
    at createViewNodes (http://localhost:8100/build/vendor.js:14158:53)
    at createRootView (http://localhost:8100/build/vendor.js:14047:5)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:15472:42)
    at Object.debugCreateRootView [as createRootView] (http://localhost:8100/build/vendor.js:14755:12)
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:19174)
    at OverlayPortal.NavControllerBase._fireError (http://localhost:8100/build/vendor.js:51699:16)
    at OverlayPortal.NavControllerBase._failed (http://localhost:8100/build/vendor.js:51692:14)
    at http://localhost:8100/build/vendor.js:51739:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:5134:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
    at r.run (http://localhost:8100/build/polyfills.js:3:10143)
    at http://localhost:8100/build/polyfills.js:3:20242

Can you please suggest a solution for this or a workaround?

**Comment by MahmoudAlsahban22** [comment]
Try add the attributes and the functions of the home page in the demo project (the following link)

https://github.com/misha130/ion-datepicker/blob/master/demo/src/pages/home/home.ts
